experimenter : 'AB'                    # experimenter initials in capital letters
animalID: ''                       
speciesID: ''                        
sex: ''                                # 'female' or 'male'
repro_state: ''                        # 'mother' or 'father' or 'virgin' or 'mated' or 'pregnant'
exp_num: '01'                          # '01', '02' etc.
beh_paradigm_id: ''                    # (pr = pup retrieval, rm = retrieval motivation)
photometry: ''                         # 'yes' or 'no'
viral_injection_date: ''               # yyyy-mm-dd
virus_id: ''                           # virus identifier 
virus_target: ''                       # anatomical target region 
video_duration_mins: 1                 # in minutes
camera_preview: True                   # if True, picams are displaying a review, if False no picam displays a review 
illumination: 'RL'                     # # IR or dimmed room light (RL)
