---
- hosts: all
  vars:
    source_directory: "{{ source_directory }}"
  tasks:
    - name: Set timestamp fact
      set_fact:
        timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{ ansible_date_time.second }}"

    - name: Copy config.yaml to Pis
      copy:
        src:  "{{ source_directory }}/config.yaml"
        dest: "/home/pi/Desktop/scripts/{{ timestamp }}_config.yaml"
      become: yes

- hosts: rpi1
  tasks:
    - name: Print the time when main.py is initiated
      debug:
        msg: "main.py initiated at {{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Start main.py on rpi1
      command: python3 "/home/pi/Desktop/picam_sync_neuro/code/raspberry_pis/main.py" "/home/pi/Desktop/scripts/{{ timestamp }}_config.yaml"
      async: 10000
      poll: 0
      
- hosts: rpi2
  tasks:
    - name: Print the time when main.py is initiated
      debug:
        msg: "main.py initiated at {{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Start main.py on rpi2 
      command: python3 "/home/pi/Desktop/picam_sync_neuro/code/raspberry_pis/main.py" "/home/pi/Desktop/scripts/{{ timestamp }}_config.yaml"
      async: 10000
      poll: 0
